// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCca3h9NHsTh-XhLKFDwOx07-X-Fpg_-u0',
    appId: '1:121426968554:web:bd20dae7d70cfe4e2e7c93',
    messagingSenderId: '121426968554',
    projectId: 'bm-typer-app',
    authDomain: 'bm-typer-app.firebaseapp.com',
    storageBucket: 'bm-typer-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQTo2z4p19AEhHrq7RiVZ7RW_IFmT2nU',
    appId: '1:121426968554:android:0b0d5850c9ede54e2e7c93',
    messagingSenderId: '121426968554',
    projectId: 'bm-typer-app',
    storageBucket: 'bm-typer-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpRbtuB9AG4EkTdVu0XdaXABilOBaw2ZI',
    appId: '1:121426968554:ios:7e417586613265742e7c93',
    messagingSenderId: '121426968554',
    projectId: 'bm-typer-app',
    storageBucket: 'bm-typer-app.firebasestorage.app',
    iosBundleId: 'com.example.bmTyper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCca3h9NHsTh-XhLKFDwOx07-X-Fpg_-u0',
    appId: '1:121426968554:web:ff7fce78095a862f2e7c93',
    messagingSenderId: '121426968554',
    projectId: 'bm-typer-app',
    authDomain: 'bm-typer-app.firebaseapp.com',
    storageBucket: 'bm-typer-app.firebasestorage.app',
  );

}